name: IEFFEUM
channels:
  - pytorch
  - nvidia/label/cuda-11.7.1
  - pyg
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.7
  - pip:
    - pandas
    - omegaconf
    - pytorch_lightning==2.1
    - biopython
    - ml_collections
    - einops
    - py3Dmol
    - modelcif
    - dm-tree
    - torch==2.0.1
    - torchvision==0.15.2
    - torchaudio==2.0.2
    - git+https://github.com/NVIDIA/dllogger.git
    - git+https://github.com/sokrypton/openfold.git
    - git+https://github.com/facebookresearch/esm.git
    - pyg_lib
    - torch_scatter
    - torch_sparse
    - torch_cluster
    - torch_spline_conv
    - torch_geometric
    - biotite
    - transformers
    - sentencepiece
    - numpy==1.26.1